/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.Global;
import Modelos.Cliente;
import Modelos.Factura;
import Modelos.Pedido;
import Modelos.Repartidor;
import Modelos.Transporte;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author berth
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();    
        reiniciar();
    }
    
    public void reiniciar(){
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton6.setEnabled(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        cliente = null;
        pedido = null;
        repartidor = null;
        transporte = null;
        factura = null;
    }
    
    public static Cliente cliente;
    public static Pedido pedido;
    public static Repartidor repartidor;
    public static Transporte transporte;
    public static Factura factura;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btCliente = new javax.swing.JButton();
        btHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btPedido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btRepartidor = new javax.swing.JButton();
        btTransporte = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btFactura = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panelPie = new javax.swing.JPanel();
        lbMensaje = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Académico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setPreferredSize(new java.awt.Dimension(550, 420));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cliente (1).png"))); // NOI18N
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 80, 70));

        btCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCliente.setForeground(new java.awt.Color(255, 255, 255));
        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo.png"))); // NOI18N
        btCliente.setText("Cliente");
        btCliente.setBorder(null);
        btCliente.setContentAreaFilled(false);
        btCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo2.png"))); // NOI18N
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        panelMenu.add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 208, 70));

        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/home.jpg"))); // NOI18N
        btHome.setBorderPainted(false);
        btHome.setContentAreaFilled(false);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        panelMenu.add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/banner.jpg"))); // NOI18N
        panelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pedido.png"))); // NOI18N
        panelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 70));

        btPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPedido.setForeground(new java.awt.Color(255, 255, 255));
        btPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo.png"))); // NOI18N
        btPedido.setText("Pedido");
        btPedido.setBorder(null);
        btPedido.setContentAreaFilled(false);
        btPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPedido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo2.png"))); // NOI18N
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });
        panelMenu.add(btPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 208, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/repartidor.png"))); // NOI18N
        panelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 90, 80));

        btRepartidor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        btRepartidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo.png"))); // NOI18N
        btRepartidor.setText("Repartidor");
        btRepartidor.setBorder(null);
        btRepartidor.setContentAreaFilled(false);
        btRepartidor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRepartidor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo2.png"))); // NOI18N
        btRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRepartidorActionPerformed(evt);
            }
        });
        panelMenu.add(btRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 208, 70));

        btTransporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTransporte.setForeground(new java.awt.Color(255, 255, 255));
        btTransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo.png"))); // NOI18N
        btTransporte.setText("Transporte");
        btTransporte.setBorder(null);
        btTransporte.setContentAreaFilled(false);
        btTransporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTransporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo2.png"))); // NOI18N
        btTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransporteActionPerformed(evt);
            }
        });
        panelMenu.add(btTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 208, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transporte.png"))); // NOI18N
        panelMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 80, 70));

        btFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btFactura.setForeground(new java.awt.Color(255, 255, 255));
        btFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo.png"))); // NOI18N
        btFactura.setText("Factura");
        btFactura.setBorder(null);
        btFactura.setContentAreaFilled(false);
        btFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFactura.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/botonrojo2.png"))); // NOI18N
        btFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturaActionPerformed(evt);
            }
        });
        panelMenu.add(btFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 208, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/factura.png"))); // NOI18N
        panelMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 70, 70));

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setMinimumSize(new java.awt.Dimension(1000, 980));
        panelCentral.setPreferredSize(new java.awt.Dimension(1100, 980));
        panelCentral.setLayout(new java.awt.CardLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        jLabel8.setText("REALIZA TU PEDIDO AHORA!!!");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("1. Selecciona o agrega un cliente:");

        jButton1.setText("Ir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Cliente:");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("2. Escoje un repartidor:");

        jButton2.setText("Ir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Repartidor:");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("3. Escoje un transporte:");

        jButton3.setText("Ir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Placa:");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("4. Crea un pedido:");

        jButton4.setText("Ir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Codigo pedido:");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("NUEVO PEDIDO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("GENERAR FACTURA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton2))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton3))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton4))
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1102, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        panelCentral.add(panelFondo, "card2");

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        panelPie.setBackground(new java.awt.Color(255, 51, 51));
        panelPie.setPreferredSize(new java.awt.Dimension(1400, 50));
        panelPie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMensaje.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbMensaje.setForeground(new java.awt.Color(255, 255, 255));
        panelPie.add(lbMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 5, 800, 40));

        jLabel7.setText("Copyright UTMACH 2023");
        panelPie.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 50));

        getContentPane().add(panelPie, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        String path=Global.getPath();
        //Icono de la aplicación
        ImageIcon icon = new ImageIcon(path+ "\\Recursos\\icono_app.png");
        setIconImage(icon.getImage());  
        setExtendedState(this.getExtendedState() | frmPrincipal.MAXIMIZED_BOTH); //maximizar
        //agregar todos los paneles creados
        panelCentral.add(panelFondo, "Fondo");
        panelCentral.add(new panelCliente(""),"Cliente");
        panelCentral.add(new panelFactura(""),"Factura");
        panelCentral.add(new panelPedido(""),"Pedido");
        panelCentral.add(new panelRepartidor(""),"Repartidor");
        panelCentral.add(new panelTransporte(""),"Transporte");
    }//GEN-LAST:event_formWindowActivated

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
       try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Cliente");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btClienteActionPerformed

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Fondo");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Pedido");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btPedidoActionPerformed

    private void btRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRepartidorActionPerformed
        // TODO add your handling code here:
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Repartidor");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btRepartidorActionPerformed

    private void btTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransporteActionPerformed
        // TODO add your handling code here:
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Transporte");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btTransporteActionPerformed

    private void btFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturaActionPerformed
        // TODO add your handling code here:
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Factura");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btFacturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelCliente pc = new panelCliente("Pedido");
        panelCentral.add(pc,"ClientePedido");
        
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "ClientePedido");
        }catch(Exception ex){}
        panelCentral.repaint();
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panelRepartidor pc = new panelRepartidor("Pedido");
        panelCentral.add(pc,"RepartidorPedido");
        
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "RepartidorPedido");
        }catch(Exception ex){}
        panelCentral.repaint();
        jButton2.setEnabled(false);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        panelTransporte pc = new panelTransporte("Pedido");
        panelCentral.add(pc,"TransportePedido");
        
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "TransportePedido");
        }catch(Exception ex){}
        panelCentral.repaint();
        jButton3.setEnabled(false);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        panelPedido pc = new panelPedido("Pedido");
        panelCentral.add(pc,"pedidoPedido");
        
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "pedidoPedido");
        }catch(Exception ex){}
        panelCentral.repaint();
        jButton4.setEnabled(false);
        jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        reiniciar();
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(cliente==null||pedido==null||repartidor==null||transporte==null){
            lbMensaje.setText("Procedimiento ingresado incorrectamente!!");
            reiniciar();
        }else{
            factura = new Factura(0, pedido.Codigo_pedido, cliente.Cedula_cliente, cliente.Nombre, cliente.Apellido, cliente.Telefono, cliente.Direccion_domicilio, cliente.Ciudad, "");
            panelFactura pc = new panelFactura("Pedido");
            panelCentral.add(pc,"facturaPedido");
            try{
                CardLayout cl = (CardLayout)(panelCentral.getLayout());
                cl.show(panelCentral, "facturaPedido");
            }catch(Exception ex){}
            panelCentral.repaint();
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    public static void mostrarMain(String ob){
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Fondo");
        }catch(Exception ex){}
        panelCentral.repaint();
        if(ob.equals("Cliente")){
            jTextField1.setText(cliente.Nombre+" "+cliente.Apellido);
        }
        if(ob.equals("Repartidor")){
            jTextField2.setText(repartidor.Nombre+" "+repartidor.Apellido);
        }
        if(ob.equals("Transporte")){
            jTextField3.setText(transporte.Placa);
        }
        if(ob.equals("Pedido")){
            jTextField4.setText(pedido.Codigo_pedido);
            lbMensaje.setText("Pedido ordenado correctamente");
        }
        
    }
    
    public static void mostrarFactura(){
        panelCentral.add(new panelDatosClientes(),"panelFinalFactura");
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "panelFinalFactura");
        }catch(Exception ex){}
        panelCentral.repaint();   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btFactura;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btPedido;
    private javax.swing.JButton btRepartidor;
    private javax.swing.JButton btTransporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField3;
    private static javax.swing.JTextField jTextField4;
    public static javax.swing.JLabel lbMensaje;
    private static javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPie;
    // End of variables declaration//GEN-END:variables
}
