/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelos.Factura;

/**
 *
 * @author negri
 */
public class panelDatosClientes extends javax.swing.JPanel {

    /**
     * Creates new form panelDatosClientes
     */
    public panelDatosClientes() {
        initComponents();
        Factura fc = frmPrincipal.factura;
        txtNumfac.setText("Numero de factura: "+fc.Num_fact);
        txtCodpe.setText("Codigo pedido: "+fc.Codigo_pedido);
        txtCedcli.setText("Cedula cliente: "+fc.Cedula_cliente);
        txtNombre.setText("Nombre: "+fc.Nombre);
        txtApellido.setText("Apellido: "+fc.Apellido);
        txtTelefono.setText("Telefono: "+fc.Telefono);
        txtDireccion.setText("Direccion Domicilio: "+fc.Direccion_domicilio);
        txtCiudad.setText("Ciudad:"+fc.Ciudad);
        txtFecha.setText("Fecha de venta: "+fc.Fecha_venta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodpe = new javax.swing.JLabel();
        txtCedcli = new javax.swing.JLabel();
        txtNumfac = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JLabel();

        txtCodpe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCodpe.setText("jLabel2");

        txtCedcli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedcli.setText("jLabel2");

        txtNumfac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumfac.setText("jLabel2");

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellido.setText("jLabel2");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setText("jLabel2");

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDireccion.setText("jLabel2");

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.setText("jLabel2");

        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFecha.setText("jLabel2");

        txtCiudad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCiudad.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumfac, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addComponent(txtCodpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCedcli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtNumfac)
                .addGap(18, 18, 18)
                .addComponent(txtCodpe)
                .addGap(18, 18, 18)
                .addComponent(txtCedcli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre)
                .addGap(18, 18, 18)
                .addComponent(txtApellido)
                .addGap(18, 18, 18)
                .addComponent(txtTelefono)
                .addGap(18, 18, 18)
                .addComponent(txtDireccion)
                .addGap(18, 18, 18)
                .addComponent(txtCiudad)
                .addGap(18, 18, 18)
                .addComponent(txtFecha)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCedcli;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtCodpe;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNumfac;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
